tabItem(tabName = "scsel",
        h4("Welcome to SciView!"),
        tags$hr(),
        shiny::HTML("SciViewer is an interactive visualization platform for single cell datasets. 
                             This section allows you to browse the study for a list of available studies. 
                             The second section of the platform allows exploration of a selected single cell dataset using multiple interactive plots.
                             These plots and data visualizations are highly customizable -depending on the project needs. 
                             The visualizations are gene-centric.
                             In the last section, you can compare the expression of a selected gene across multiple datasets. The gene expression comparison
                             across studies is qualitative, but can give an understanding of the expression patterns of the gene across two selected studies. 
                             The platform further allows visualization of CITE-seq data. 
                             <br><br>"),
        
        tags$br(),
        box(
                #shiny::HTML("Explore folder containing study databases"),
                shiny::HTML("The <b>Add more studies!</b> button allows you to chose the folder locations from the hard-drive (/home; .; C:/  ).
                             Please select appropriate folder that contains database files (.db) for single cell experiments. Please note that the 
                             database files are generated by <i><u>SciViewerIn</u></i> application by using the single cell data in either Seurat or .h5ad format.  
                              
                             If the directory of choice is not availalbe, please input the directory path in the box below and then explore the folder 
                             using <b>Add more studies!</b> button.<br> "),
                tags$br(),
                fluidRow(column(width=6,textInput("datadir", "browse directory path", NULL)),
                         column(width=4,tags$br(),actionButton("ab573dfg3","Go!",icon = icon("arrows-rotate"))),
                         column(width=2)
                ),
                verbatimTextOutput('direxists'),
                tags$br(),
                shinyFilesButton(id = 'infile', label = '+ Add more studies!',title =  'Please select a dataset', multiple = T),
                tags$br(),
                solidHeader = T, collapsible = T,collapsed = T, width = 12, 
                title = h6("Explore folder containing study databases", style = 'font-size:14px;color:black;')
        ),
        shiny::HTML("<br><br>"),
        tags$br(),
        h4("Select scRNA-seq study"),
        tags$hr(),
        shiny::HTML("You can filter the available studies for species, disease, tissue, user-defined cell type or sample size. 
                             The selected study from the list is available for further data exploration. The details of the selected study 
                              are displayed at the end of the page."),
        #selectInput("sc_study",label="",choices = NULL,multiple = F),
        tags$br(),
        #-- table 
        DT::dataTableOutput("browse_studytable") %>% shinycssloaders::withSpinner(color="#0dc5c1"),
        tags$br(),
        box(
                shiny::HTML("<b> Details of the selected study:</b><br>"), 
                htmlOutput("sc_study_attribs"),
                solidHeader = T, collapsible = F,collapsed = F, width = 12
        ),
        tags$br()
)## End of scsel
